### PR TITLE
move common cmse definitions from BSP to tee

### LINKED ISSUE #41: move common cmse definitions from BSP to tee
currently mTower use device related definitions which will lead to build fail when porting new device, and that's not good for a common function.

### PR DESCRIPTION
**Pull request by onlinedj**
Signed-off-by: Jacky Yang <yangxinle@xiaomi.com>

# Description

we are porting new devices to mTower, and find tee has some dependency on BSP definitions, so we hope to seperate them apart.

Fixes #41 move common cmse definitions from BSP to tee

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] These are only definitions location change, build get passed for numaker_pfm_m2351

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by onlinedj** [comment]
@tdrozdovsky please help review if it is reasonable to do so

**Comment by tdrozdovsky** [comment]
Fine, I'll see how to do it!

**Comment by onlinedj** [comment]
image
workflow needs your approval.

**Comment by onlinedj** [comment]
@tdrozdovsky  anything update?

**Comment by onlinedj** [comment]
@tdrozdovsky  anything update?

**Comment by tdrozdovsky** [comment]
Check if the request is still relevant

**Pull request closed without merging**
